### ISSUE TITLE
read_h5ad in R fails when file path has spaces

### ISSUE THREAD

**Issue by taprati** [JiekaiLab/scDIOR#5]
I was attempting to use the read_h5ad function in R, but I ran into an error that there was no such file or directory. After looking into it, I believe this is due to my file path containing spaces, as I can see that when R passes the arguments to diorPy.py in the shell, the file name has the spaces, which would definitely invoke an error. Not sure if this was known/ if this can be mitigated. Thanks

**Comment by fenghuijian** [comment]
Thank you for using our software. read_h5ad may have some problems, we recommend to use write_h5 & read_h5 for  data conversion. We will now update our software for bug fixes.

**Comment by FionaMoon** [comment]
Hi,
I also met this problem ,which not happen in the past.
```
adata = diopy.input.read_h5(file = 'for.python.h5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xtdisk/miniconda/envs/py39/lib/python3.9/site-packages/diopy/input.py", line 51, in read_h5
    h5 = h5py.File(name=file, mode='r')
  File "/xtdisk/miniconda/envs/py39/lib/python3.9/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/xtdiskminiconda/envs/py39/lib/python3.9/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: [Errno 37] Unable to open file (unable to lock file, errno = 37, error message = 'No locks available')
```
